[package]
name = "simple-crud"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

diesel = { version = "^2.2.4", features = ["sqlite"] }
dotenv = "0.15.0"

uuid = { version = "^1.11.0", features = ["serde", "v4"] }